# Azure Pipeline to deploy CloudOps Managed DevOps Pools using Deployment Stacks
# This pipeline deploys the CloudOps Bicep template as a Deployment Stack at subscription scope
# Deploys Managed DevOps Pool with native scale-to-zero support
# Prerequisites:
# - Stage 1: CloudOps subscription created via sub-vending pipeline
# - Stage 2: CloudOps spoke networking deployed via spoke-networking pipeline
# - Stage 3: DevCenter deployed via cloudops-devcenter-pipeline

trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: common-variables
  - name: bicepPath
    value: "code/bicep/cloudops"
  - name: templateFile
    value: "$(bicepPath)/cloudops.bicep"
  - name: parametersFile
    value: "$(bicepPath)/cloudops.bicepparam"
  - name: stackName
    value: "stack-${{ parameters.workloadAlias }}-${{ parameters.environment }}-${{ parameters.locationCode }}-${{ parameters.instanceNumber }}"

parameters:
  # Target CloudOps subscription (from Stage 1)
  - name: subscriptionId
    displayName: "CloudOps Subscription ID (from sub-vending)"
    type: string
    default: ""
  # Core naming parameters
  - name: workloadAlias
    displayName: "Workload Alias"
    type: string
    default: "cloudops"
  - name: environment
    displayName: "Environment"
    type: string
    default: "live"
    values:
      - nonprod
      - dev
      - test
      - uat
      - staging
      - prod
      - live
  - name: locationCode
    displayName: "Location Code (e.g., cac for canada central)"
    type: string
    default: "cac"
  - name: instanceNumber
    displayName: "Instance Number (e.g., 001 for the first instance)"
    type: string
    default: "001"
  - name: location
    displayName: "Azure Region"
    type: string
    default: "canadacentral"
  # Ownership
  - name: owner
    displayName: "Owner (e.g., platform-team@example.com)"
    type: string
    default: ""
  - name: managedBy
    displayName: "Managed By"
    type: string
    default: "Bicep"
  # DevCenter references (from Stage 3)
  - name: devCenterResourceId
    displayName: "DevCenter Resource ID (from cloudops-devcenter-pipeline)"
    type: string
    default: ""
  # Spoke networking references (from Stage 2)
  - name: poolSubnetResourceId
    displayName: "Pool Subnet Resource ID (from spoke-networking)"
    type: string
    default: ""
  # Managed DevOps Pool Configuration
  - name: poolMaximumConcurrency
    displayName: "Maximum Pool Concurrency (agent count)"
    type: number
    default: 4
  - name: poolAgentSkuName
    displayName: "Pool Agent VM SKU"
    type: string
    default: "Standard_D4s_v5"
  - name: poolImageName
    displayName: "Pool Image Name"
    type: string
    default: "ubuntu-22.04/latest"
    values:
      - ubuntu-22.04/latest
      - ubuntu-24.04/latest
      - windows-2022/latest
      - windows-2019/latest
  - name: enableScaleToZero
    displayName: "Enable Scale-to-Zero (cost optimization)"
    type: boolean
    default: true
  # Azure DevOps Configuration
  - name: azureDevOpsOrganizationUrl
    displayName: "Azure DevOps Organization URL (e.g., https://dev.azure.com/myorg)"
    type: string
    default: ""
  - name: azureDevOpsProjectNames
    displayName: "Azure DevOps Project Names (comma-separated, leave empty for org-wide)"
    type: string
    default: ""
  # Deployment Stack settings
  - name: denySettingsMode
    displayName: "Deny Settings Mode"
    type: string
    default: "denyWriteAndDelete"
    values:
      - none
      - denyDelete
      - denyWriteAndDelete
  - name: actionOnUnmanage
    displayName: "Action on Unmanaged Resources"
    type: string
    default: "detachAll"
    values:
      - deleteResources
      - deleteAll
      - detachAll
  - name: deploymentStage
    displayName: "Pipeline Stage to Run"
    type: string
    default: "WhatIf"
    values:
      - Validation
      - WhatIf
      - Deploy

stages:
  - stage: Validate
    displayName: "Validate Deployment Stack"
    # Runs for: Validation, WhatIf, Deploy (all options)
    jobs:
      - job: ValidateStack
        displayName: "Validate Stack"
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "Validate CloudOps Deployment Stack"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                PARAMS=""
                # Core naming parameters
                if [ -n "${{ parameters.workloadAlias }}" ]; then
                  PARAMS="$PARAMS --parameters workloadAlias='${{ parameters.workloadAlias }}'"
                fi
                if [ -n "${{ parameters.environment }}" ]; then
                  PARAMS="$PARAMS --parameters environment='${{ parameters.environment }}'"
                fi
                if [ -n "${{ parameters.locationCode }}" ]; then
                  PARAMS="$PARAMS --parameters locationCode='${{ parameters.locationCode }}'"
                fi
                if [ -n "${{ parameters.instanceNumber }}" ]; then
                  PARAMS="$PARAMS --parameters instanceNumber='${{ parameters.instanceNumber }}'"
                fi
                if [ -n "${{ parameters.location }}" ]; then
                  PARAMS="$PARAMS --parameters location='${{ parameters.location }}'"
                fi
                # Ownership
                if [ -n "${{ parameters.owner }}" ]; then
                  PARAMS="$PARAMS --parameters owner='${{ parameters.owner }}'"
                fi
                if [ -n "${{ parameters.managedBy }}" ]; then
                  PARAMS="$PARAMS --parameters managedBy='${{ parameters.managedBy }}'"
                fi
                # DevCenter references
                if [ -n "${{ parameters.devCenterResourceId }}" ]; then
                  PARAMS="$PARAMS --parameters devCenterResourceId='${{ parameters.devCenterResourceId }}'"
                fi
                # Spoke networking references
                if [ -n "${{ parameters.poolSubnetResourceId }}" ]; then
                  PARAMS="$PARAMS --parameters poolSubnetResourceId='${{ parameters.poolSubnetResourceId }}'"
                fi
                # Managed DevOps Pool Configuration
                PARAMS="$PARAMS --parameters poolMaximumConcurrency=${{ parameters.poolMaximumConcurrency }}"
                if [ -n "${{ parameters.poolAgentSkuName }}" ]; then
                  PARAMS="$PARAMS --parameters poolAgentSkuName='${{ parameters.poolAgentSkuName }}'"
                fi
                if [ -n "${{ parameters.poolImageName }}" ]; then
                  PARAMS="$PARAMS --parameters poolImageName='${{ parameters.poolImageName }}'"
                fi
                PARAMS="$PARAMS --parameters enableScaleToZero=${{ parameters.enableScaleToZero }}"
                # Azure DevOps Configuration
                if [ -n "${{ parameters.azureDevOpsOrganizationUrl }}" ]; then
                  PARAMS="$PARAMS --parameters azureDevOpsOrganizationUrl='${{ parameters.azureDevOpsOrganizationUrl }}'"
                fi
                # Handle project names as array
                PROJECT_NAMES="${{ parameters.azureDevOpsProjectNames }}"
                if [ -n "$PROJECT_NAMES" ]; then
                  # Convert comma-separated string to JSON array
                  PROJECT_ARRAY=$(echo "$PROJECT_NAMES" | jq -R 'split(",") | map(gsub("^\\s+|\\s+$";""))')
                  PARAMS="$PARAMS --parameters azureDevOpsProjectNames='$PROJECT_ARRAY'"
                fi

                az stack sub validate \
                  --name "stack-${{ parameters.workloadAlias }}-${{ parameters.environment }}-${{ parameters.locationCode }}-${{ parameters.instanceNumber }}" \
                  --subscription "${{ parameters.subscriptionId }}" \
                  --location $(deploymentLocation) \
                  --template-file $(templateFile) \
                  --parameters $(parametersFile) \
                  --deny-settings-mode ${{ parameters.denySettingsMode }} \
                  --action-on-unmanage ${{ parameters.actionOnUnmanage }} \
                  $PARAMS

  - stage: WhatIf
    displayName: "What-If Analysis"
    dependsOn:
      - Validate
    # Runs for: WhatIf, Deploy
    condition: |
      and(
        eq(dependencies.Validate.result, 'Succeeded'),
        in('${{ parameters.deploymentStage }}', 'WhatIf', 'Deploy')
      )
    jobs:
      - job: WhatIfAnalysis
        displayName: "What-If"
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "What-If CloudOps Deployment Stack"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                PARAMS=""
                # Core naming parameters
                if [ -n "${{ parameters.workloadAlias }}" ]; then
                  PARAMS="$PARAMS --parameters workloadAlias='${{ parameters.workloadAlias }}'"
                fi
                if [ -n "${{ parameters.environment }}" ]; then
                  PARAMS="$PARAMS --parameters environment='${{ parameters.environment }}'"
                fi
                if [ -n "${{ parameters.locationCode }}" ]; then
                  PARAMS="$PARAMS --parameters locationCode='${{ parameters.locationCode }}'"
                fi
                if [ -n "${{ parameters.instanceNumber }}" ]; then
                  PARAMS="$PARAMS --parameters instanceNumber='${{ parameters.instanceNumber }}'"
                fi
                if [ -n "${{ parameters.location }}" ]; then
                  PARAMS="$PARAMS --parameters location='${{ parameters.location }}'"
                fi
                # Ownership
                if [ -n "${{ parameters.owner }}" ]; then
                  PARAMS="$PARAMS --parameters owner='${{ parameters.owner }}'"
                fi
                if [ -n "${{ parameters.managedBy }}" ]; then
                  PARAMS="$PARAMS --parameters managedBy='${{ parameters.managedBy }}'"
                fi
                # DevCenter references
                if [ -n "${{ parameters.devCenterResourceId }}" ]; then
                  PARAMS="$PARAMS --parameters devCenterResourceId='${{ parameters.devCenterResourceId }}'"
                fi
                # Spoke networking references
                if [ -n "${{ parameters.poolSubnetResourceId }}" ]; then
                  PARAMS="$PARAMS --parameters poolSubnetResourceId='${{ parameters.poolSubnetResourceId }}'"
                fi
                # Managed DevOps Pool Configuration
                PARAMS="$PARAMS --parameters poolMaximumConcurrency=${{ parameters.poolMaximumConcurrency }}"
                if [ -n "${{ parameters.poolAgentSkuName }}" ]; then
                  PARAMS="$PARAMS --parameters poolAgentSkuName='${{ parameters.poolAgentSkuName }}'"
                fi
                if [ -n "${{ parameters.poolImageName }}" ]; then
                  PARAMS="$PARAMS --parameters poolImageName='${{ parameters.poolImageName }}'"
                fi
                PARAMS="$PARAMS --parameters enableScaleToZero=${{ parameters.enableScaleToZero }}"
                # Azure DevOps Configuration
                if [ -n "${{ parameters.azureDevOpsOrganizationUrl }}" ]; then
                  PARAMS="$PARAMS --parameters azureDevOpsOrganizationUrl='${{ parameters.azureDevOpsOrganizationUrl }}'"
                fi
                # Handle project names as array
                PROJECT_NAMES="${{ parameters.azureDevOpsProjectNames }}"
                if [ -n "$PROJECT_NAMES" ]; then
                  # Convert comma-separated string to JSON array
                  PROJECT_ARRAY=$(echo "$PROJECT_NAMES" | jq -R 'split(",") | map(gsub("^\\s+|\\s+$";""))')
                  PARAMS="$PARAMS --parameters azureDevOpsProjectNames='$PROJECT_ARRAY'"
                fi

                az stack sub create \
                  --name "stack-${{ parameters.workloadAlias }}-${{ parameters.environment }}-${{ parameters.locationCode }}-${{ parameters.instanceNumber }}" \
                  --subscription "${{ parameters.subscriptionId }}" \
                  --location $(deploymentLocation) \
                  --template-file $(templateFile) \
                  --parameters $(parametersFile) \
                  --deny-settings-mode ${{ parameters.denySettingsMode }} \
                  --action-on-unmanage ${{ parameters.actionOnUnmanage }} \
                  --what-if \
                  $PARAMS

  - stage: Deploy
    displayName: "Deploy CloudOps Deployment Stack"
    dependsOn:
      - Validate
      - WhatIf
    # Runs for: Deploy only
    condition: |
      and(
        eq(dependencies.Validate.result, 'Succeeded'),
        in(dependencies.WhatIf.result, 'Succeeded', 'Skipped'),
        eq('${{ parameters.deploymentStage }}', 'Deploy')
      )
    jobs:
      - deployment: DeployCloudOpsStack
        displayName: "Deploy CloudOps Stack"
        environment: "cloudops"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: "Deploy CloudOps Deployment Stack"
                  inputs:
                    azureSubscription: "$(azureServiceConnection)"
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      PARAMS=""
                      # Core naming parameters
                      if [ -n "${{ parameters.workloadAlias }}" ]; then
                        PARAMS="$PARAMS --parameters workloadAlias='${{ parameters.workloadAlias }}'"
                      fi
                      if [ -n "${{ parameters.environment }}" ]; then
                        PARAMS="$PARAMS --parameters environment='${{ parameters.environment }}'"
                      fi
                      if [ -n "${{ parameters.locationCode }}" ]; then
                        PARAMS="$PARAMS --parameters locationCode='${{ parameters.locationCode }}'"
                      fi
                      if [ -n "${{ parameters.instanceNumber }}" ]; then
                        PARAMS="$PARAMS --parameters instanceNumber='${{ parameters.instanceNumber }}'"
                      fi
                      if [ -n "${{ parameters.location }}" ]; then
                        PARAMS="$PARAMS --parameters location='${{ parameters.location }}'"
                      fi
                      # Ownership
                      if [ -n "${{ parameters.owner }}" ]; then
                        PARAMS="$PARAMS --parameters owner='${{ parameters.owner }}'"
                      fi
                      if [ -n "${{ parameters.managedBy }}" ]; then
                        PARAMS="$PARAMS --parameters managedBy='${{ parameters.managedBy }}'"
                      fi
                      # DevCenter references
                      if [ -n "${{ parameters.devCenterResourceId }}" ]; then
                        PARAMS="$PARAMS --parameters devCenterResourceId='${{ parameters.devCenterResourceId }}'"
                      fi
                      # Spoke networking references
                      if [ -n "${{ parameters.poolSubnetResourceId }}" ]; then
                        PARAMS="$PARAMS --parameters poolSubnetResourceId='${{ parameters.poolSubnetResourceId }}'"
                      fi
                      # Managed DevOps Pool Configuration
                      PARAMS="$PARAMS --parameters poolMaximumConcurrency=${{ parameters.poolMaximumConcurrency }}"
                      if [ -n "${{ parameters.poolAgentSkuName }}" ]; then
                        PARAMS="$PARAMS --parameters poolAgentSkuName='${{ parameters.poolAgentSkuName }}'"
                      fi
                      if [ -n "${{ parameters.poolImageName }}" ]; then
                        PARAMS="$PARAMS --parameters poolImageName='${{ parameters.poolImageName }}'"
                      fi
                      PARAMS="$PARAMS --parameters enableScaleToZero=${{ parameters.enableScaleToZero }}"
                      # Azure DevOps Configuration
                      if [ -n "${{ parameters.azureDevOpsOrganizationUrl }}" ]; then
                        PARAMS="$PARAMS --parameters azureDevOpsOrganizationUrl='${{ parameters.azureDevOpsOrganizationUrl }}'"
                      fi
                      # Handle project names as array
                      PROJECT_NAMES="${{ parameters.azureDevOpsProjectNames }}"
                      if [ -n "$PROJECT_NAMES" ]; then
                        # Convert comma-separated string to JSON array
                        PROJECT_ARRAY=$(echo "$PROJECT_NAMES" | jq -R 'split(",") | map(gsub("^\\s+|\\s+$";""))')
                        PARAMS="$PARAMS --parameters azureDevOpsProjectNames='$PROJECT_ARRAY'"
                      fi

                      az stack sub create \
                        --name "stack-${{ parameters.workloadAlias }}-${{ parameters.environment }}-${{ parameters.locationCode }}-${{ parameters.instanceNumber }}" \
                        --subscription "${{ parameters.subscriptionId }}" \
                        --location $(deploymentLocation) \
                        --template-file $(templateFile) \
                        --parameters $(parametersFile) \
                        --deny-settings-mode ${{ parameters.denySettingsMode }} \
                        --action-on-unmanage ${{ parameters.actionOnUnmanage }} \
                        --yes \
                        $PARAMS
