# Azure Pipeline to deploy Hub Infrastructure using Deployment Stacks
# This pipeline deploys the hub Bicep template as a Deployment Stack at subscription scope
# Deploys hub networking infrastructure including VNet, Network Watcher, Private DNS, AVNM, and optional resources

trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: common-variables
  - name: bicepPath
    value: "code/bicep/hub"
  - name: templateFile
    value: "$(bicepPath)/hub.bicep"
  - name: parametersFile
    value: "$(bicepPath)/hub.bicepparam"
  - name: stackName
    value: "stack-${{ parameters.purpose }}-${{ parameters.environment }}-${{ parameters.locationCode }}-${{ parameters.instanceNumber }}"

parameters:
  - name: subscriptionId
    displayName: "Hub Subscription ID"
    type: string
    default: ""
  - name: purpose
    displayName: "Purpose"
    type: string
    default: "hub"
  - name: environment
    displayName: "Environment"
    type: string
    default: "live"
    values:
      - nonprod
      - dev
      - test
      - uat
      - staging
      - prod
      - live
  - name: locationCode
    displayName: "Location Code (e.g., cac for canada central)"
    type: string
    default: "cac"
  - name: instanceNumber
    displayName: "Instance Number (e.g., 001 for the first instance)"
    type: string
    default: "001"
  - name: location
    displayName: "Azure Region"
    type: string
    default: "canadacentral"
  - name: privateDnsZoneName
    displayName: "Private DNS Zone Name"
    type: string
    default: "internal.organization.com"
  - name: hubVnetAddressSpace
    displayName: "Hub VNet Address Space"
    type: string
    default: "10.0.0.0/16"
  - name: logAnalyticsWorkspaceResourceId
    displayName: "Log Analytics Workspace Resource ID (from monitoring infrastructure)"
    type: string
  - name: owner
    displayName: "Owner (e.g. a group mailbox like platform-team@example.com)"
    type: string
  - name: managedBy
    displayName: "Managed By"
    type: string
    default: "Bicep"
  - name: avnmManagementGroupId
    displayName: "AVNM Management Group ID"
    type: string
    default: "mg-connectivity"
  # Optional resource flags
  - name: enableAppGatewayWAF
    displayName: "Enable Application Gateway with WAF"
    type: boolean
    default: false
  - name: enableFrontDoor
    displayName: "Enable Azure Front Door (Standard)"
    type: boolean
    default: false
  - name: enableVpnGateway
    displayName: "Enable VPN Gateway with P2S"
    type: boolean
    default: false
  - name: enableAzureFirewall
    displayName: "Enable Azure Firewall"
    type: boolean
    default: false
  - name: enableDDoSProtection
    displayName: "Enable DDoS Protection"
    type: boolean
    default: false
  - name: enableDnsResolver
    displayName: "Enable Private DNS Resolver"
    type: boolean
    default: false
  - name: enableIpamPool
    displayName: "Enable IPAM Pool"
    type: boolean
    default: false
  - name: ipamPoolAddressSpace
    displayName: "IPAM Pool Address Space"
    type: string
    default: "10.0.0.0/8"
  - name: ipamPoolDescription
    displayName: "IPAM Pool Description"
    type: string
    default: "Centralized IPAM pool for hub and spoke networks"
  # Optional resource configuration
  - name: vpnClientAddressPoolPrefix
    displayName: "VPN Client Address Pool Prefix (for P2S)"
    type: string
    default: "172.16.0.0/24"
  - name: azureFirewallTier
    displayName: "Azure Firewall SKU Tier"
    type: string
    default: "Standard"
    values:
      - Standard
      - Premium
  # Deployment Stack settings
  - name: denySettingsMode
    displayName: "Deny Settings Mode"
    type: string
    default: "denyWriteAndDelete"
    values:
      - none
      - denyDelete
      - denyWriteAndDelete
  - name: actionOnUnmanage
    displayName: "Action on Unmanaged Resources"
    type: string
    default: "detachAll"
    values:
      - deleteResources
      - deleteAll
      - detachAll
  - name: deploymentStage
    displayName: "Pipeline Stage to Run"
    type: string
    default: "WhatIf"
    values:
      - Validation
      - WhatIf
      - Deploy

stages:
  - stage: Validate
    displayName: "Validate Deployment Stack"
    # Runs for: Validation, WhatIf, Deploy (all options)
    jobs:
      - job: ValidateStack
        displayName: "Validate Stack"
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "Validate Hub Deployment Stack"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                PARAMS=""
                if [ -n "${{ parameters.purpose }}" ]; then
                  PARAMS="$PARAMS --parameters purpose='${{ parameters.purpose }}'"
                fi
                if [ -n "${{ parameters.environment }}" ]; then
                  PARAMS="$PARAMS --parameters environment='${{ parameters.environment }}'"
                fi
                if [ -n "${{ parameters.locationCode }}" ]; then
                  PARAMS="$PARAMS --parameters locationCode='${{ parameters.locationCode }}'"
                fi
                if [ -n "${{ parameters.instanceNumber }}" ]; then
                  PARAMS="$PARAMS --parameters instanceNumber='${{ parameters.instanceNumber }}'"
                fi
                if [ -n "${{ parameters.location }}" ]; then
                  PARAMS="$PARAMS --parameters location='${{ parameters.location }}'"
                fi
                if [ -n "${{ parameters.privateDnsZoneName }}" ]; then
                  PARAMS="$PARAMS --parameters privateDnsZoneName='${{ parameters.privateDnsZoneName }}'"
                fi
                if [ -n "${{ parameters.hubVnetAddressSpace }}" ]; then
                  PARAMS="$PARAMS --parameters hubVnetAddressSpace='${{ parameters.hubVnetAddressSpace }}'"
                fi
                if [ -n "${{ parameters.logAnalyticsWorkspaceResourceId }}" ]; then
                  PARAMS="$PARAMS --parameters logAnalyticsWorkspaceResourceId='${{ parameters.logAnalyticsWorkspaceResourceId }}'"
                fi
                if [ -n "${{ parameters.owner }}" ]; then
                  PARAMS="$PARAMS --parameters owner='${{ parameters.owner }}'"
                fi
                if [ -n "${{ parameters.managedBy }}" ]; then
                  PARAMS="$PARAMS --parameters managedBy='${{ parameters.managedBy }}'"
                fi
                if [ -n "${{ parameters.avnmManagementGroupId }}" ]; then
                  PARAMS="$PARAMS --parameters avnmManagementGroupId='${{ parameters.avnmManagementGroupId }}'"
                fi
                # Optional resource flags
                PARAMS="$PARAMS --parameters enableAppGatewayWAF=${{ parameters.enableAppGatewayWAF }}"
                PARAMS="$PARAMS --parameters enableFrontDoor=${{ parameters.enableFrontDoor }}"
                PARAMS="$PARAMS --parameters enableVpnGateway=${{ parameters.enableVpnGateway }}"
                PARAMS="$PARAMS --parameters enableAzureFirewall=${{ parameters.enableAzureFirewall }}"
                PARAMS="$PARAMS --parameters enableDDoSProtection=${{ parameters.enableDDoSProtection }}"
                PARAMS="$PARAMS --parameters enableDnsResolver=${{ parameters.enableDnsResolver }}"
                PARAMS="$PARAMS --parameters enableIpamPool=${{ parameters.enableIpamPool }}"
                if [ -n "${{ parameters.ipamPoolAddressSpace }}" ]; then
                  PARAMS="$PARAMS --parameters ipamPoolAddressSpace='${{ parameters.ipamPoolAddressSpace }}'"
                fi
                if [ -n "${{ parameters.ipamPoolDescription }}" ]; then
                  PARAMS="$PARAMS --parameters ipamPoolDescription='${{ parameters.ipamPoolDescription }}'"
                fi
                # Optional resource configuration
                if [ -n "${{ parameters.vpnClientAddressPoolPrefix }}" ]; then
                  PARAMS="$PARAMS --parameters vpnClientAddressPoolPrefix='${{ parameters.vpnClientAddressPoolPrefix }}'"
                fi
                if [ -n "${{ parameters.azureFirewallTier }}" ]; then
                  PARAMS="$PARAMS --parameters azureFirewallTier='${{ parameters.azureFirewallTier }}'"
                fi

                az stack sub validate \
                  --name "stack-${{ parameters.purpose }}-${{ parameters.environment }}-${{ parameters.locationCode }}-${{ parameters.instanceNumber }}" \
                  --subscription "${{ parameters.subscriptionId }}" \
                  --location $(deploymentLocation) \
                  --template-file $(templateFile) \
                  --parameters $(parametersFile) \
                  --deny-settings-mode ${{ parameters.denySettingsMode }} \
                  --action-on-unmanage ${{ parameters.actionOnUnmanage }} \
                  $PARAMS

  - stage: WhatIf
    displayName: "What-If Analysis"
    dependsOn:
      - Validate
    # Runs for: WhatIf, Deploy
    condition: |
      and(
        eq(dependencies.Validate.result, 'Succeeded'),
        in('${{ parameters.deploymentStage }}', 'WhatIf', 'Deploy')
      )
    jobs:
      - job: WhatIfAnalysis
        displayName: "What-If"
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "What-If Hub Deployment Stack"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                PARAMS=""
                if [ -n "${{ parameters.purpose }}" ]; then
                  PARAMS="$PARAMS --parameters purpose='${{ parameters.purpose }}'"
                fi
                if [ -n "${{ parameters.environment }}" ]; then
                  PARAMS="$PARAMS --parameters environment='${{ parameters.environment }}'"
                fi
                if [ -n "${{ parameters.locationCode }}" ]; then
                  PARAMS="$PARAMS --parameters locationCode='${{ parameters.locationCode }}'"
                fi
                if [ -n "${{ parameters.instanceNumber }}" ]; then
                  PARAMS="$PARAMS --parameters instanceNumber='${{ parameters.instanceNumber }}'"
                fi
                if [ -n "${{ parameters.location }}" ]; then
                  PARAMS="$PARAMS --parameters location='${{ parameters.location }}'"
                fi
                if [ -n "${{ parameters.privateDnsZoneName }}" ]; then
                  PARAMS="$PARAMS --parameters privateDnsZoneName='${{ parameters.privateDnsZoneName }}'"
                fi
                if [ -n "${{ parameters.hubVnetAddressSpace }}" ]; then
                  PARAMS="$PARAMS --parameters hubVnetAddressSpace='${{ parameters.hubVnetAddressSpace }}'"
                fi
                if [ -n "${{ parameters.logAnalyticsWorkspaceResourceId }}" ]; then
                  PARAMS="$PARAMS --parameters logAnalyticsWorkspaceResourceId='${{ parameters.logAnalyticsWorkspaceResourceId }}'"
                fi
                if [ -n "${{ parameters.owner }}" ]; then
                  PARAMS="$PARAMS --parameters owner='${{ parameters.owner }}'"
                fi
                if [ -n "${{ parameters.managedBy }}" ]; then
                  PARAMS="$PARAMS --parameters managedBy='${{ parameters.managedBy }}'"
                fi
                if [ -n "${{ parameters.avnmManagementGroupId }}" ]; then
                  PARAMS="$PARAMS --parameters avnmManagementGroupId='${{ parameters.avnmManagementGroupId }}'"
                fi
                # Optional resource flags
                PARAMS="$PARAMS --parameters enableAppGatewayWAF=${{ parameters.enableAppGatewayWAF }}"
                PARAMS="$PARAMS --parameters enableFrontDoor=${{ parameters.enableFrontDoor }}"
                PARAMS="$PARAMS --parameters enableVpnGateway=${{ parameters.enableVpnGateway }}"
                PARAMS="$PARAMS --parameters enableAzureFirewall=${{ parameters.enableAzureFirewall }}"
                PARAMS="$PARAMS --parameters enableDDoSProtection=${{ parameters.enableDDoSProtection }}"
                PARAMS="$PARAMS --parameters enableDnsResolver=${{ parameters.enableDnsResolver }}"
                PARAMS="$PARAMS --parameters enableIpamPool=${{ parameters.enableIpamPool }}"
                if [ -n "${{ parameters.ipamPoolAddressSpace }}" ]; then
                  PARAMS="$PARAMS --parameters ipamPoolAddressSpace='${{ parameters.ipamPoolAddressSpace }}'"
                fi
                if [ -n "${{ parameters.ipamPoolDescription }}" ]; then
                  PARAMS="$PARAMS --parameters ipamPoolDescription='${{ parameters.ipamPoolDescription }}'"
                fi
                # Optional resource configuration
                if [ -n "${{ parameters.vpnClientAddressPoolPrefix }}" ]; then
                  PARAMS="$PARAMS --parameters vpnClientAddressPoolPrefix='${{ parameters.vpnClientAddressPoolPrefix }}'"
                fi
                if [ -n "${{ parameters.azureFirewallTier }}" ]; then
                  PARAMS="$PARAMS --parameters azureFirewallTier='${{ parameters.azureFirewallTier }}'"
                fi

                az stack sub create \
                  --name "stack-${{ parameters.purpose }}-${{ parameters.environment }}-${{ parameters.locationCode }}-${{ parameters.instanceNumber }}" \
                  --subscription "${{ parameters.subscriptionId }}" \
                  --location $(deploymentLocation) \
                  --template-file $(templateFile) \
                  --parameters $(parametersFile) \
                  --deny-settings-mode ${{ parameters.denySettingsMode }} \
                  --action-on-unmanage ${{ parameters.actionOnUnmanage }} \
                  --what-if \
                  $PARAMS

  - stage: Deploy
    displayName: "Deploy Hub Deployment Stack"
    dependsOn:
      - Validate
      - WhatIf
    # Runs for: Deploy only
    condition: |
      and(
        eq(dependencies.Validate.result, 'Succeeded'),
        in(dependencies.WhatIf.result, 'Succeeded', 'Skipped'),
        eq('${{ parameters.deploymentStage }}', 'Deploy')
      )
    jobs:
      - deployment: DeployHubStack
        displayName: "Deploy Hub Stack"
        environment: "hub"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: "Deploy Hub Deployment Stack"
                  inputs:
                    azureSubscription: "$(azureServiceConnection)"
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      PARAMS=""
                      if [ -n "${{ parameters.purpose }}" ]; then
                        PARAMS="$PARAMS --parameters purpose='${{ parameters.purpose }}'"
                      fi
                      if [ -n "${{ parameters.environment }}" ]; then
                        PARAMS="$PARAMS --parameters environment='${{ parameters.environment }}'"
                      fi
                      if [ -n "${{ parameters.locationCode }}" ]; then
                        PARAMS="$PARAMS --parameters locationCode='${{ parameters.locationCode }}'"
                      fi
                      if [ -n "${{ parameters.instanceNumber }}" ]; then
                        PARAMS="$PARAMS --parameters instanceNumber='${{ parameters.instanceNumber }}'"
                      fi
                      if [ -n "${{ parameters.location }}" ]; then
                        PARAMS="$PARAMS --parameters location='${{ parameters.location }}'"
                      fi
                      if [ -n "${{ parameters.privateDnsZoneName }}" ]; then
                        PARAMS="$PARAMS --parameters privateDnsZoneName='${{ parameters.privateDnsZoneName }}'"
                      fi
                      if [ -n "${{ parameters.hubVnetAddressSpace }}" ]; then
                        PARAMS="$PARAMS --parameters hubVnetAddressSpace='${{ parameters.hubVnetAddressSpace }}'"
                      fi
                      if [ -n "${{ parameters.logAnalyticsWorkspaceResourceId }}" ]; then
                        PARAMS="$PARAMS --parameters logAnalyticsWorkspaceResourceId='${{ parameters.logAnalyticsWorkspaceResourceId }}'"
                      fi
                      if [ -n "${{ parameters.owner }}" ]; then
                        PARAMS="$PARAMS --parameters owner='${{ parameters.owner }}'"
                      fi
                      if [ -n "${{ parameters.managedBy }}" ]; then
                        PARAMS="$PARAMS --parameters managedBy='${{ parameters.managedBy }}'"
                      fi
                      if [ -n "${{ parameters.avnmManagementGroupId }}" ]; then
                        PARAMS="$PARAMS --parameters avnmManagementGroupId='${{ parameters.avnmManagementGroupId }}'"
                      fi
                      # Optional resource flags
                      PARAMS="$PARAMS --parameters enableAppGatewayWAF=${{ parameters.enableAppGatewayWAF }}"
                      PARAMS="$PARAMS --parameters enableFrontDoor=${{ parameters.enableFrontDoor }}"
                      PARAMS="$PARAMS --parameters enableVpnGateway=${{ parameters.enableVpnGateway }}"
                      PARAMS="$PARAMS --parameters enableAzureFirewall=${{ parameters.enableAzureFirewall }}"
                      PARAMS="$PARAMS --parameters enableDDoSProtection=${{ parameters.enableDDoSProtection }}"
                      PARAMS="$PARAMS --parameters enableDnsResolver=${{ parameters.enableDnsResolver }}"
                      PARAMS="$PARAMS --parameters enableIpamPool=${{ parameters.enableIpamPool }}"
                      if [ -n "${{ parameters.ipamPoolAddressSpace }}" ]; then
                        PARAMS="$PARAMS --parameters ipamPoolAddressSpace='${{ parameters.ipamPoolAddressSpace }}'"
                      fi
                      if [ -n "${{ parameters.ipamPoolDescription }}" ]; then
                        PARAMS="$PARAMS --parameters ipamPoolDescription='${{ parameters.ipamPoolDescription }}'"
                      fi
                      # Optional resource configuration
                      if [ -n "${{ parameters.vpnClientAddressPoolPrefix }}" ]; then
                        PARAMS="$PARAMS --parameters vpnClientAddressPoolPrefix='${{ parameters.vpnClientAddressPoolPrefix }}'"
                      fi
                      if [ -n "${{ parameters.azureFirewallTier }}" ]; then
                        PARAMS="$PARAMS --parameters azureFirewallTier='${{ parameters.azureFirewallTier }}'"
                      fi

                      az stack sub create \
                        --name "stack-${{ parameters.purpose }}-${{ parameters.environment }}-${{ parameters.locationCode }}-${{ parameters.instanceNumber }}" \
                        --subscription "${{ parameters.subscriptionId }}" \
                        --location $(deploymentLocation) \
                        --template-file $(templateFile) \
                        --parameters $(parametersFile) \
                        --deny-settings-mode ${{ parameters.denySettingsMode }} \
                        --action-on-unmanage ${{ parameters.actionOnUnmanage }} \
                        --yes \
                        $PARAMS
