# Azure Pipeline to deploy Management Group Hierarchy
# This pipeline deploys the mg-hierarchy Bicep template at the management group scope
#
# =============================================================================
# RBAC REQUIREMENTS
# =============================================================================
# The service principal used by the Azure service connection requires BOTH of
# the following roles assigned at the Tenant Root Management Group:
#
#   1. Management Group Contributor - To create/update/delete management groups
#   2. Contributor - For Microsoft.Resources/deployments/write permission
#
# Why both roles are needed:
#   The Management Group Contributor role alone does NOT include the
#   Microsoft.Resources/deployments/write permission. ARM deployments create
#   deployment resources at each management group scope. Since child management
#   groups don't exist during initial deployment, these permissions must be
#   inherited from the Tenant Root Group via the Contributor role.
#
# To assign these roles, run (as Owner/User Access Administrator):
#
#   SP_OBJECT_ID="<service-principal-object-id>"
#   TENANT_ROOT_MG=$(az account management-group list \
#     --query "[?displayName=='Tenant Root Group'].name" -o tsv)
#
#   az role assignment create --assignee "$SP_OBJECT_ID" \
#     --role "Management Group Contributor" \
#     --scope "/providers/Microsoft.Management/managementGroups/$TENANT_ROOT_MG"
#
#   az role assignment create --assignee "$SP_OBJECT_ID" \
#     --role "Contributor" \
#     --scope "/providers/Microsoft.Management/managementGroups/$TENANT_ROOT_MG"
#
# See docs/Management-Group-Hierarchy/Creating-Management-Group-Hierarchy.md
# for full documentation.
# =============================================================================

trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: common-variables
  - group: mg-hierarchy-variables
  - name: bicepPath
    value: "code/bicep/mg-hierarchy"
  - name: templateFile
    value: "$(bicepPath)/mg-hierarchy.bicep"
  - name: parametersFile
    value: "$(bicepPath)/mg-hierarchy.bicepparam"

parameters:
  - name: deploymentStage
    displayName: "Pipeline Stage to Run"
    type: string
    default: "WhatIf"
    values:
      - Validation
      - WhatIf
      - Deploy

stages:
  - stage: Validate
    displayName: "Validate Bicep Template"
    # Runs for: Validation, WhatIf, Deploy (all options)
    jobs:
      - job: ValidateBicep
        displayName: "Validate Bicep"
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "Validate Management Group Deployment"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az deployment mg validate \
                  --management-group-id $(azureTenantId) \
                  --location $(deploymentLocation) \
                  --template-file $(templateFile) \
                  --parameters $(parametersFile) \
                  --parameters tenantRootManagementGroupId=$(azureTenantId) \
                  --parameters orgName="$(orgName)" \
                  --parameters orgDisplayName="$(orgDisplayName)"

  - stage: WhatIf
    displayName: "What-If Analysis"
    dependsOn:
      - Validate
    # Runs for: WhatIf, Deploy
    condition: |
      and(
        eq(dependencies.Validate.result, 'Succeeded'),
        in('${{ parameters.deploymentStage }}', 'WhatIf', 'Deploy')
      )
    jobs:
      - job: WhatIfAnalysis
        displayName: "What-If"
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "What-If Management Group Deployment"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az deployment mg what-if \
                  --management-group-id $(azureTenantId) \
                  --location $(deploymentLocation) \
                  --template-file $(templateFile) \
                  --parameters $(parametersFile) \
                  --parameters tenantRootManagementGroupId=$(azureTenantId) \
                  --parameters orgName="$(orgName)" \
                  --parameters orgDisplayName="$(orgDisplayName)"

  - stage: Deploy
    displayName: "Deploy Management Group Hierarchy"
    dependsOn:
      - Validate
      - WhatIf
    # Runs for: Deploy only
    condition: |
      and(
        eq(dependencies.Validate.result, 'Succeeded'),
        in(dependencies.WhatIf.result, 'Succeeded', 'Skipped'),
        eq('${{ parameters.deploymentStage }}', 'Deploy')
      )
    jobs:
      - deployment: DeployMgHierarchy
        displayName: "Deploy MG Hierarchy"
        environment: "management-groups"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: "Deploy Management Group Hierarchy"
                  inputs:
                    azureSubscription: "$(azureServiceConnection)"
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      az deployment mg create \
                        --name 'mg-hierarchy-$(Build.BuildNumber)' \
                        --management-group-id $(azureTenantId) \
                        --location $(deploymentLocation) \
                        --template-file $(templateFile) \
                        --parameters $(parametersFile) \
                        --parameters tenantRootManagementGroupId=$(azureTenantId) \
                        --parameters orgName="$(orgName)" \
                        --parameters orgDisplayName="$(orgDisplayName)"
