# Azure Pipeline to deploy Monitoring Infrastructure
# This pipeline deploys the monitoring Bicep template at the subscription scope
# Deploys centralized Log Analytics workspace to the monitoring subscription

trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: common-variables
  - name: bicepPath
    value: "code/bicep/monitoring"
  - name: templateFile
    value: "$(bicepPath)/monitoring.bicep"
  - name: parametersFile
    value: "$(bicepPath)/monitoring.bicepparam"

parameters:
  - name: subscriptionId
    displayName: "Monitoring Subscription ID"
    type: string
    default: ""
  - name: purpose
    displayName: "Purpose"
    type: string
    default: "monitoring"
  - name: environment
    displayName: "Environment"
    type: string
    default: "live"
    values:
      - nonprod
      - dev
      - test
      - uat
      - staging
      - prod
      - live
  - name: locationCode
    displayName: "Location Code (e.g., cac for canada central)"
    type: string
    default: "cac"
  - name: instanceNumber
    displayName: "Instance Number (e.g., 001 for the first instance)"
    type: string
    default: "001"
  - name: location
    displayName: "Azure Region"
    type: string
    default: "canadacentral"
  - name: dataRetention
    displayName: "Data Retention (days)"
    type: number
    default: 60
  - name: owner
    displayName: "Owner"
    type: string
    default: "platform-team"
  - name: managedBy
    displayName: "Managed By"
    type: string
    default: "Bicep"
  - name: deploymentStage
    displayName: "Pipeline Stage to Run"
    type: string
    default: "WhatIf"
    values:
      - Validation
      - WhatIf
      - Deploy

stages:
  - stage: Validate
    displayName: "Validate Bicep Template"
    # Runs for: Validation, WhatIf, Deploy (all options)
    jobs:
      - job: ValidateBicep
        displayName: "Validate Bicep"
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "Validate Monitoring Deployment"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                PARAMS=""
                if [ -n "${{ parameters.purpose }}" ]; then
                  PARAMS="$PARAMS --parameters purpose='${{ parameters.purpose }}'"
                fi
                if [ -n "${{ parameters.environment }}" ]; then
                  PARAMS="$PARAMS --parameters environment='${{ parameters.environment }}'"
                fi
                if [ -n "${{ parameters.locationCode }}" ]; then
                  PARAMS="$PARAMS --parameters locationCode='${{ parameters.locationCode }}'"
                fi
                if [ -n "${{ parameters.instanceNumber }}" ]; then
                  PARAMS="$PARAMS --parameters instanceNumber='${{ parameters.instanceNumber }}'"
                fi
                if [ -n "${{ parameters.location }}" ]; then
                  PARAMS="$PARAMS --parameters location='${{ parameters.location }}'"
                fi
                if [ -n "${{ parameters.dataRetention }}" ]; then
                  PARAMS="$PARAMS --parameters dataRetention=${{ parameters.dataRetention }}"
                fi
                if [ -n "${{ parameters.owner }}" ]; then
                  PARAMS="$PARAMS --parameters owner='${{ parameters.owner }}'"
                fi
                if [ -n "${{ parameters.managedBy }}" ]; then
                  PARAMS="$PARAMS --parameters managedBy='${{ parameters.managedBy }}'"
                fi

                az deployment sub validate \
                  --subscription "${{ parameters.subscriptionId }}" \
                  --location $(deploymentLocation) \
                  --template-file $(templateFile) \
                  --parameters $(parametersFile) \
                  $PARAMS

  - stage: WhatIf
    displayName: "What-If Analysis"
    dependsOn:
      - Validate
    # Runs for: WhatIf, Deploy
    condition: |
      and(
        eq(dependencies.Validate.result, 'Succeeded'),
        in('${{ parameters.deploymentStage }}', 'WhatIf', 'Deploy')
      )
    jobs:
      - job: WhatIfAnalysis
        displayName: "What-If"
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "What-If Monitoring Deployment"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                PARAMS=""
                if [ -n "${{ parameters.purpose }}" ]; then
                  PARAMS="$PARAMS --parameters purpose='${{ parameters.purpose }}'"
                fi
                if [ -n "${{ parameters.environment }}" ]; then
                  PARAMS="$PARAMS --parameters environment='${{ parameters.environment }}'"
                fi
                if [ -n "${{ parameters.locationCode }}" ]; then
                  PARAMS="$PARAMS --parameters locationCode='${{ parameters.locationCode }}'"
                fi
                if [ -n "${{ parameters.instanceNumber }}" ]; then
                  PARAMS="$PARAMS --parameters instanceNumber='${{ parameters.instanceNumber }}'"
                fi
                if [ -n "${{ parameters.location }}" ]; then
                  PARAMS="$PARAMS --parameters location='${{ parameters.location }}'"
                fi
                if [ -n "${{ parameters.dataRetention }}" ]; then
                  PARAMS="$PARAMS --parameters dataRetention=${{ parameters.dataRetention }}"
                fi
                if [ -n "${{ parameters.owner }}" ]; then
                  PARAMS="$PARAMS --parameters owner='${{ parameters.owner }}'"
                fi
                if [ -n "${{ parameters.managedBy }}" ]; then
                  PARAMS="$PARAMS --parameters managedBy='${{ parameters.managedBy }}'"
                fi

                az deployment sub what-if \
                  --subscription "${{ parameters.subscriptionId }}" \
                  --location $(deploymentLocation) \
                  --template-file $(templateFile) \
                  --parameters $(parametersFile) \
                  $PARAMS

  - stage: Deploy
    displayName: "Deploy Monitoring Infrastructure"
    dependsOn:
      - Validate
      - WhatIf
    # Runs for: Deploy only
    condition: |
      and(
        eq(dependencies.Validate.result, 'Succeeded'),
        in(dependencies.WhatIf.result, 'Succeeded', 'Skipped'),
        eq('${{ parameters.deploymentStage }}', 'Deploy')
      )
    jobs:
      - deployment: DeployMonitoring
        displayName: "Deploy Monitoring"
        environment: "monitoring"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: "Deploy Monitoring Infrastructure"
                  inputs:
                    azureSubscription: "$(azureServiceConnection)"
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      PARAMS=""
                      if [ -n "${{ parameters.purpose }}" ]; then
                        PARAMS="$PARAMS --parameters purpose='${{ parameters.purpose }}'"
                      fi
                      if [ -n "${{ parameters.environment }}" ]; then
                        PARAMS="$PARAMS --parameters environment='${{ parameters.environment }}'"
                      fi
                      if [ -n "${{ parameters.locationCode }}" ]; then
                        PARAMS="$PARAMS --parameters locationCode='${{ parameters.locationCode }}'"
                      fi
                      if [ -n "${{ parameters.instanceNumber }}" ]; then
                        PARAMS="$PARAMS --parameters instanceNumber='${{ parameters.instanceNumber }}'"
                      fi
                      if [ -n "${{ parameters.location }}" ]; then
                        PARAMS="$PARAMS --parameters location='${{ parameters.location }}'"
                      fi
                      if [ -n "${{ parameters.dataRetention }}" ]; then
                        PARAMS="$PARAMS --parameters dataRetention=${{ parameters.dataRetention }}"
                      fi
                      if [ -n "${{ parameters.owner }}" ]; then
                        PARAMS="$PARAMS --parameters owner='${{ parameters.owner }}'"
                      fi
                      if [ -n "${{ parameters.managedBy }}" ]; then
                        PARAMS="$PARAMS --parameters managedBy='${{ parameters.managedBy }}'"
                      fi

                      az deployment sub create \
                        --name 'monitoring-$(Build.BuildNumber)' \
                        --subscription "${{ parameters.subscriptionId }}" \
                        --location $(deploymentLocation) \
                        --template-file $(templateFile) \
                        --parameters $(parametersFile) \
                        $PARAMS
