# Azure Pipeline to deploy Monitoring Infrastructure using Deployment Stacks
# This pipeline deploys the monitoring Bicep template as a Deployment Stack at subscription scope
# Deploys centralized Log Analytics workspace to the monitoring subscription

trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: common-variables
  - name: bicepPath
    value: "code/bicep/monitoring"
  - name: templateFile
    value: "$(bicepPath)/monitoring.bicep"
  - name: parametersFile
    value: "$(bicepPath)/monitoring.bicepparam"
  - name: stackName
    value: "stack-monitoring-${{ parameters.environment }}-${{ parameters.locationCode }}-${{ parameters.instanceNumber }}"

parameters:
  - name: subscriptionId
    displayName: "Monitoring Subscription ID"
    type: string
    default: ""
  - name: workloadAlias
    displayName: "Workload Alias"
    type: string
    default: "monitoring"
  - name: environment
    displayName: "Environment"
    type: string
    default: "live"
    values:
      - nonprod
      - dev
      - test
      - uat
      - staging
      - prod
      - live
  - name: locationCode
    displayName: "Location Code (e.g., cac for canada central)"
    type: string
    default: "cac"
  - name: instanceNumber
    displayName: "Instance Number (e.g., 001 for the first instance)"
    type: string
    default: "001"
  - name: location
    displayName: "Azure Region"
    type: string
    default: "canadacentral"
  - name: dataRetention
    displayName: "Data Retention (days)"
    type: number
    default: 60
  - name: owner
    displayName: "Owner (e.g. a group mailbox like platform-team@example.com)"
    type: string
  - name: managedBy
    displayName: "Managed By"
    type: string
    default: "Bicep"
  - name: dailyQuotaGb
    displayName: "Daily Ingestion Quota in GB (-1 for unlimited)"
    type: number
    default: -1
  - name: alertEmailAddresses
    displayName: "Alert Email Addresses (semicolon separated, leave empty to disable alerts)"
    type: string
    default: ""
  - name: alertWebhookUri
    displayName: "Alert Webhook URI (optional)"
    type: string
    default: ""
  - name: enableAlertRules
    displayName: "Enable Alert Rules"
    type: boolean
    default: true
  - name: diagnosticStorageAccountId
    displayName: "Storage Account Resource ID for Workspace Diagnostics (optional)"
    type: string
    default: ""
  - name: denySettingsMode
    displayName: "Deny Settings Mode"
    type: string
    default: "denyWriteAndDelete"
    values:
      - none
      - denyDelete
      - denyWriteAndDelete
  - name: actionOnUnmanage
    displayName: "Action on Unmanaged Resources"
    type: string
    default: "detachAll"
    values:
      - deleteResources
      - deleteAll
      - detachAll
  - name: deploymentStage
    displayName: "Pipeline Stage to Run"
    type: string
    default: "WhatIf"
    values:
      - Validation
      - WhatIf
      - Deploy

stages:
  - stage: Validate
    displayName: "Validate Deployment Stack"
    # Runs for: Validation, WhatIf, Deploy (all options)
    jobs:
      - job: ValidateStack
        displayName: "Validate Stack"
        steps:
          - checkout: self

          - script: |
              # Validate environment parameter against allowed environments
              ALLOWED_ENVS="$(environments)"
              ENV_PARAM="${{ parameters.environment }}"

              if [ -z "$ENV_PARAM" ]; then
                echo "##[error]Environment parameter is required but was not provided."
                echo "Allowed environments: ${ALLOWED_ENVS}"
                exit 1
              fi

              if [[ ",${ALLOWED_ENVS}," =~ ",${ENV_PARAM}," ]]; then
                echo "✓ Valid environment: ${ENV_PARAM}"
              else
                echo "##[error]Invalid environment: ${ENV_PARAM}"
                echo "Allowed environments: ${ALLOWED_ENVS}"
                exit 1
              fi
            displayName: "Validate Environment Parameter"

          - task: AzureCLI@2
            displayName: "Validate Monitoring Deployment Stack"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                PARAMS=""
                if [ -n "${{ parameters.workloadAlias }}" ]; then
                  PARAMS="$PARAMS --parameters workloadAlias='${{ parameters.workloadAlias }}'"
                fi
                if [ -n "${{ parameters.environment }}" ]; then
                  PARAMS="$PARAMS --parameters environment='${{ parameters.environment }}'"
                fi
                if [ -n "${{ parameters.locationCode }}" ]; then
                  PARAMS="$PARAMS --parameters locationCode='${{ parameters.locationCode }}'"
                fi
                if [ -n "${{ parameters.instanceNumber }}" ]; then
                  PARAMS="$PARAMS --parameters instanceNumber='${{ parameters.instanceNumber }}'"
                fi
                if [ -n "${{ parameters.location }}" ]; then
                  PARAMS="$PARAMS --parameters location='${{ parameters.location }}'"
                fi
                if [ -n "${{ parameters.dataRetention }}" ]; then
                  PARAMS="$PARAMS --parameters dataRetention=${{ parameters.dataRetention }}"
                fi
                if [ -n "${{ parameters.owner }}" ]; then
                  PARAMS="$PARAMS --parameters owner='${{ parameters.owner }}'"
                fi
                if [ -n "${{ parameters.managedBy }}" ]; then
                  PARAMS="$PARAMS --parameters managedBy='${{ parameters.managedBy }}'"
                fi
                if [ -n "${{ parameters.dailyQuotaGb }}" ]; then
                  PARAMS="$PARAMS --parameters dailyQuotaGb=${{ parameters.dailyQuotaGb }}"
                fi
                if [ -n "${{ parameters.alertEmailAddresses }}" ]; then
                  PARAMS="$PARAMS --parameters alertEmailAddresses='${{ parameters.alertEmailAddresses }}'"
                fi
                if [ -n "${{ parameters.alertWebhookUri }}" ]; then
                  PARAMS="$PARAMS --parameters alertWebhookUri='${{ parameters.alertWebhookUri }}'"
                fi
                if [ "${{ parameters.enableAlertRules }}" == "true" ] || [ "${{ parameters.enableAlertRules }}" == "True" ]; then
                  PARAMS="$PARAMS --parameters enableAlertRules=true"
                else
                  PARAMS="$PARAMS --parameters enableAlertRules=false"
                fi
                if [ -n "${{ parameters.diagnosticStorageAccountId }}" ]; then
                  PARAMS="$PARAMS --parameters diagnosticStorageAccountId='${{ parameters.diagnosticStorageAccountId }}'"
                fi

                az stack sub validate \
                  --name "stack-${{ parameters.workloadAlias }}-${{ parameters.environment }}-${{ parameters.locationCode }}-${{ parameters.instanceNumber }}" \
                  --subscription "${{ parameters.subscriptionId }}" \
                  --location $(deploymentLocation) \
                  --template-file $(templateFile) \
                  --parameters $(parametersFile) \
                  --deny-settings-mode ${{ parameters.denySettingsMode }} \
                  --action-on-unmanage ${{ parameters.actionOnUnmanage }} \
                  $PARAMS

  - stage: WhatIf
    displayName: "What-If Analysis"
    dependsOn:
      - Validate
    # Runs for: WhatIf, Deploy
    condition: |
      and(
        eq(dependencies.Validate.result, 'Succeeded'),
        in('${{ parameters.deploymentStage }}', 'WhatIf', 'Deploy')
      )
    jobs:
      - job: WhatIfAnalysis
        displayName: "What-If"
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "What-If Monitoring Deployment Stack"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                PARAMS=""
                if [ -n "${{ parameters.workloadAlias }}" ]; then
                  PARAMS="$PARAMS --parameters workloadAlias='${{ parameters.workloadAlias }}'"
                fi
                if [ -n "${{ parameters.environment }}" ]; then
                  PARAMS="$PARAMS --parameters environment='${{ parameters.environment }}'"
                fi
                if [ -n "${{ parameters.locationCode }}" ]; then
                  PARAMS="$PARAMS --parameters locationCode='${{ parameters.locationCode }}'"
                fi
                if [ -n "${{ parameters.instanceNumber }}" ]; then
                  PARAMS="$PARAMS --parameters instanceNumber='${{ parameters.instanceNumber }}'"
                fi
                if [ -n "${{ parameters.location }}" ]; then
                  PARAMS="$PARAMS --parameters location='${{ parameters.location }}'"
                fi
                if [ -n "${{ parameters.dataRetention }}" ]; then
                  PARAMS="$PARAMS --parameters dataRetention=${{ parameters.dataRetention }}"
                fi
                if [ -n "${{ parameters.owner }}" ]; then
                  PARAMS="$PARAMS --parameters owner='${{ parameters.owner }}'"
                fi
                if [ -n "${{ parameters.managedBy }}" ]; then
                  PARAMS="$PARAMS --parameters managedBy='${{ parameters.managedBy }}'"
                fi
                if [ -n "${{ parameters.dailyQuotaGb }}" ]; then
                  PARAMS="$PARAMS --parameters dailyQuotaGb=${{ parameters.dailyQuotaGb }}"
                fi
                if [ -n "${{ parameters.alertEmailAddresses }}" ]; then
                  PARAMS="$PARAMS --parameters alertEmailAddresses='${{ parameters.alertEmailAddresses }}'"
                fi
                if [ -n "${{ parameters.alertWebhookUri }}" ]; then
                  PARAMS="$PARAMS --parameters alertWebhookUri='${{ parameters.alertWebhookUri }}'"
                fi
                if [ "${{ parameters.enableAlertRules }}" == "true" ] || [ "${{ parameters.enableAlertRules }}" == "True" ]; then
                  PARAMS="$PARAMS --parameters enableAlertRules=true"
                else
                  PARAMS="$PARAMS --parameters enableAlertRules=false"
                fi
                if [ -n "${{ parameters.diagnosticStorageAccountId }}" ]; then
                  PARAMS="$PARAMS --parameters diagnosticStorageAccountId='${{ parameters.diagnosticStorageAccountId }}'"
                fi

                az stack sub create \
                  --name "stack-${{ parameters.workloadAlias }}-${{ parameters.environment }}-${{ parameters.locationCode }}-${{ parameters.instanceNumber }}" \
                  --subscription "${{ parameters.subscriptionId }}" \
                  --location $(deploymentLocation) \
                  --template-file $(templateFile) \
                  --parameters $(parametersFile) \
                  --deny-settings-mode ${{ parameters.denySettingsMode }} \
                  --action-on-unmanage ${{ parameters.actionOnUnmanage }} \
                  --what-if \
                  $PARAMS

  - stage: Deploy
    displayName: "Deploy Monitoring Deployment Stack"
    dependsOn:
      - Validate
      - WhatIf
    # Runs for: Deploy only
    condition: |
      and(
        eq(dependencies.Validate.result, 'Succeeded'),
        in(dependencies.WhatIf.result, 'Succeeded', 'Skipped'),
        eq('${{ parameters.deploymentStage }}', 'Deploy')
      )
    jobs:
      - deployment: DeployMonitoringStack
        displayName: "Deploy Monitoring Stack"
        environment: "${{ parameters.environment }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: "Deploy Monitoring Deployment Stack"
                  inputs:
                    azureSubscription: "$(azureServiceConnection)"
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      PARAMS=""
                      if [ -n "${{ parameters.workloadAlias }}" ]; then
                        PARAMS="$PARAMS --parameters workloadAlias='${{ parameters.workloadAlias }}'"
                      fi
                      if [ -n "${{ parameters.environment }}" ]; then
                        PARAMS="$PARAMS --parameters environment='${{ parameters.environment }}'"
                      fi
                      if [ -n "${{ parameters.locationCode }}" ]; then
                        PARAMS="$PARAMS --parameters locationCode='${{ parameters.locationCode }}'"
                      fi
                      if [ -n "${{ parameters.instanceNumber }}" ]; then
                        PARAMS="$PARAMS --parameters instanceNumber='${{ parameters.instanceNumber }}'"
                      fi
                      if [ -n "${{ parameters.location }}" ]; then
                        PARAMS="$PARAMS --parameters location='${{ parameters.location }}'"
                      fi
                      if [ -n "${{ parameters.dataRetention }}" ]; then
                        PARAMS="$PARAMS --parameters dataRetention=${{ parameters.dataRetention }}"
                      fi
                      if [ -n "${{ parameters.owner }}" ]; then
                        PARAMS="$PARAMS --parameters owner='${{ parameters.owner }}'"
                      fi
                      if [ -n "${{ parameters.managedBy }}" ]; then
                        PARAMS="$PARAMS --parameters managedBy='${{ parameters.managedBy }}'"
                      fi
                      if [ -n "${{ parameters.dailyQuotaGb }}" ]; then
                        PARAMS="$PARAMS --parameters dailyQuotaGb=${{ parameters.dailyQuotaGb }}"
                      fi
                      if [ -n "${{ parameters.alertEmailAddresses }}" ]; then
                        PARAMS="$PARAMS --parameters alertEmailAddresses='${{ parameters.alertEmailAddresses }}'"
                      fi
                      if [ -n "${{ parameters.alertWebhookUri }}" ]; then
                        PARAMS="$PARAMS --parameters alertWebhookUri='${{ parameters.alertWebhookUri }}'"
                      fi
                      if [ "${{ parameters.enableAlertRules }}" == "true" ] || [ "${{ parameters.enableAlertRules }}" == "True" ]; then
                        PARAMS="$PARAMS --parameters enableAlertRules=true"
                      else
                        PARAMS="$PARAMS --parameters enableAlertRules=false"
                      fi
                      if [ -n "${{ parameters.diagnosticStorageAccountId }}" ]; then
                        PARAMS="$PARAMS --parameters diagnosticStorageAccountId='${{ parameters.diagnosticStorageAccountId }}'"
                      fi

                      az stack sub create \
                        --name "stack-${{ parameters.workloadAlias }}-${{ parameters.environment }}-${{ parameters.locationCode }}-${{ parameters.instanceNumber }}" \
                        --subscription "${{ parameters.subscriptionId }}" \
                        --location $(deploymentLocation) \
                        --template-file $(templateFile) \
                        --parameters $(parametersFile) \
                        --deny-settings-mode ${{ parameters.denySettingsMode }} \
                        --action-on-unmanage ${{ parameters.actionOnUnmanage }} \
                        --yes \
                        $PARAMS
