# Azure Pipeline to deploy Subscription Vending
# This pipeline deploys the sub-vending Bicep template at the tenant scope
# This pipeline is reusable and can be triggered with parameters
#
# =============================================================================
# IMPLEMENTATION NOTE
# =============================================================================
# This implementation uses direct Bicep resource definitions rather than the
# Azure Verified Module (AVM) sub-vending pattern. The AVM module was abandoned
# due to a bug where it referenced an invalid API version (2025-04-01) for
# Microsoft.Management/managementGroups. See sub-vending.bicep for details.
#
# =============================================================================
# RBAC REQUIREMENTS
# =============================================================================
# The service principal used by the Azure service connection requires:
#
#   1. Owner - At Tenant Root MG for subscription creation and MG assignment
#   2. Billing Permissions - Invoice Section Contributor (MCA) or
#                            Enrollment Account Administrator (EA)
#
# Azure RBAC assignment:
#
#   SP_OBJECT_ID="<service-principal-object-id>"
#   TENANT_ROOT_MG=$(az account management-group list \
#     --query "[?displayName=='Tenant Root Group'].name" -o tsv)
#
#   az role assignment create --assignee "$SP_OBJECT_ID" \
#     --role "Owner" \
#     --scope "/providers/Microsoft.Management/managementGroups/$TENANT_ROOT_MG"
#
# Billing permissions must be assigned via Azure Portal:
#   1. Go to Cost Management + Billing
#   2. Navigate to your billing account/invoice section
#   3. Add the SP as Invoice Section Contributor (MCA) or
#      Enrollment Account Administrator (EA)
#
# See docs/RBAC-Requirements.md for full documentation.
# =============================================================================

trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: common-variables
  - name: bicepPath
    value: "code/bicep/sub-vending"
  - name: templateFile
    value: "$(bicepPath)/sub-vending.bicep"
  - name: parametersFile
    value: "$(bicepPath)/sub-vending.bicepparam"
  - name: scriptsPath
    value: "code/pipelines/scripts"

parameters:
  - name: projectName
    displayName: "Project Name (used for tagging)"
    type: string
    default: ""
  - name: workloadAlias
    displayName: "Workload Alias (used for naming conventions)"
    type: string
    default: ""
  - name: environment
    displayName: "Environment"
    type: string
    default: ""
    values:
      - nonprod
      - dev
      - test
      - uat
      - staging
      - prod
      - live
  - name: locationCode
    displayName: "Location Code (e.g., cac for canada central)"
    type: string
    default: "cac"
  - name: instanceNumber
    displayName: "Instance Number (e.g., 001 for the first instance)"
    type: string
    default: ""
  - name: managementGroupId
    displayName: "Management Group ID"
    type: string
    default: ""
    values:
      - $(azureTenantId)
      - "mg-platform"
      - "mg-landing-zone"
      - "mg-sandbox"
      - "mg-decommissioned"
      - "mg-management"
      - "mg-connectivity"
      - "mg-corp-prod"
      - "mg-corp-non-prod"
      - "mg-online-prod"
      - "mg-online-non-prod"
  - name: workload
    displayName: "Workload Type"
    type: string
    default: "Production"
    values:
      - Production
      - DevTest
  - name: managedBy
    displayName: "Managed By"
    type: string
    default: "$(managedBy)"
  - name: owner
    displayName: "Owner"
    type: string
    default: "$(defaultOwner)"
  - name: deploymentStage
    displayName: "Pipeline Stage to Run"
    type: string
    default: "WhatIf"
    values:
      - Validation
      - WhatIf
      - Deploy

stages:
  - stage: Validate
    displayName: "Validate Bicep Template"
    # Runs for: Validation, WhatIf, Deploy (all options)
    jobs:
      - job: ValidateBicep
        displayName: "Validate Bicep"
        timeoutInMinutes: 25
        steps:
          - checkout: self

          - script: |
              # Validate environment parameter against allowed environments
              ALLOWED_ENVS="$(environments)"
              ENV_PARAM="${{ parameters.environment }}"

              if [ -z "$ENV_PARAM" ]; then
                echo "##[error]Environment parameter is required but was not provided."
                echo "Allowed environments: ${ALLOWED_ENVS}"
                exit 1
              fi

              if [[ ",${ALLOWED_ENVS}," =~ ",${ENV_PARAM}," ]]; then
                echo "✓ Valid environment: ${ENV_PARAM}"
              else
                echo "##[error]Invalid environment: ${ENV_PARAM}"
                echo "Allowed environments: ${ALLOWED_ENVS}"
                exit 1
              fi
            displayName: "Validate Environment Parameter"

          - task: AzureCLI@2
            name: LookupSubscription
            displayName: "Lookup Existing Subscription"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                bash $(scriptsPath)/lookup-subscription.sh \
                  "${{ parameters.workloadAlias }}" \
                  "${{ parameters.environment }}" \
                  "${{ parameters.locationCode }}" \
                  "${{ parameters.instanceNumber }}"

          - task: AzureCLI@2
            displayName: "Validate Subscription Vending Deployment"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                # Construct billing scope from variable group values
                BILLING_SCOPE=""
                if [ -n "$(billingAccountId)" ]; then
                  if [ -n "$(invoiceSectionId)" ] && [ -n "$(billingProfileId)" ]; then
                    # MCA billing scope format (requires billing profile)
                    BILLING_SCOPE="/providers/Microsoft.Billing/billingAccounts/$(billingAccountId)/billingProfiles/$(billingProfileId)/invoiceSections/$(invoiceSectionId)"
                  elif [ -n "$(enrollmentAccountId)" ]; then
                    # EA billing scope format
                    BILLING_SCOPE="/providers/Microsoft.Billing/billingAccounts/$(billingAccountId)/enrollmentAccounts/$(enrollmentAccountId)"
                  fi
                fi

                # Get existing subscription ID from lookup step (may be empty)
                EXISTING_SUB_ID="$(LookupSubscription.EXISTING_SUBSCRIPTION_ID)"

                az deployment tenant validate \
                  --location "$(deploymentLocation)" \
                  --template-file "$(templateFile)" \
                  --parameters "$(parametersFile)" \
                  --parameters projectName="${{ parameters.projectName }}" \
                  --parameters managementGroupId="${{ parameters.managementGroupId }}" \
                  --parameters billingScope="$BILLING_SCOPE" \
                  --parameters workload="${{ parameters.workload }}" \
                  --parameters workloadAlias="${{ parameters.workloadAlias }}" \
                  --parameters environment="${{ parameters.environment }}" \
                  --parameters locationCode="${{ parameters.locationCode }}" \
                  --parameters instanceNumber="${{ parameters.instanceNumber }}" \
                  --parameters owner="${{ parameters.owner }}" \
                  --parameters managedBy="${{ parameters.managedBy }}" \
                  --parameters existingSubscriptionId="$EXISTING_SUB_ID"

  - stage: WhatIf
    displayName: "What-If Analysis"
    dependsOn:
      - Validate
    # Runs for: WhatIf, Deploy
    condition: |
      and(
        eq(dependencies.Validate.result, 'Succeeded'),
        in('${{ parameters.deploymentStage }}', 'WhatIf', 'Deploy')
      )
    jobs:
      - job: WhatIfAnalysis
        displayName: "What-If"
        timeoutInMinutes: 25
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: LookupSubscription
            displayName: "Lookup Existing Subscription"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                bash $(scriptsPath)/lookup-subscription.sh \
                  "${{ parameters.projectName }}" \
                  "${{ parameters.workloadAlias }}" \
                  "${{ parameters.environment }}" \
                  "${{ parameters.locationCode }}" \
                  "${{ parameters.instanceNumber }}"

          - task: AzureCLI@2
            displayName: "What-If Subscription Vending Deployment"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                # Construct billing scope from variable group values
                BILLING_SCOPE=""
                if [ -n "$(billingAccountId)" ]; then
                  if [ -n "$(invoiceSectionId)" ] && [ -n "$(billingProfileId)" ]; then
                    # MCA billing scope format (requires billing profile)
                    BILLING_SCOPE="/providers/Microsoft.Billing/billingAccounts/$(billingAccountId)/billingProfiles/$(billingProfileId)/invoiceSections/$(invoiceSectionId)"
                  elif [ -n "$(enrollmentAccountId)" ]; then
                    # EA billing scope format
                    BILLING_SCOPE="/providers/Microsoft.Billing/billingAccounts/$(billingAccountId)/enrollmentAccounts/$(enrollmentAccountId)"
                  fi
                fi

                # Get existing subscription ID from lookup step (may be empty)
                EXISTING_SUB_ID="$(LookupSubscription.EXISTING_SUBSCRIPTION_ID)"

                az deployment tenant what-if \
                  --location "$(deploymentLocation)" \
                  --template-file "$(templateFile)" \
                  --parameters "$(parametersFile)" \
                  --parameters projectName="${{ parameters.projectName }}" \
                  --parameters managementGroupId="${{ parameters.managementGroupId }}" \
                  --parameters billingScope="$BILLING_SCOPE" \
                  --parameters workload="${{ parameters.workload }}" \
                  --parameters workloadAlias="${{ parameters.workloadAlias }}" \
                  --parameters environment="${{ parameters.environment }}" \
                  --parameters locationCode="${{ parameters.locationCode }}" \
                  --parameters instanceNumber="${{ parameters.instanceNumber }}" \
                  --parameters owner="${{ parameters.owner }}" \
                  --parameters managedBy="${{ parameters.managedBy }}" \
                  --parameters existingSubscriptionId="$EXISTING_SUB_ID"

  - stage: Deploy
    displayName: "Deploy Subscription Vending"
    dependsOn:
      - Validate
      - WhatIf
    # Runs for: Deploy only
    condition: |
      and(
        eq(dependencies.Validate.result, 'Succeeded'),
        in(dependencies.WhatIf.result, 'Succeeded', 'Skipped'),
        eq('${{ parameters.deploymentStage }}', 'Deploy')
      )
    jobs:
      - deployment: DeploySubscriptionVending
        displayName: "Deploy Subscription Vending"
        timeoutInMinutes: 90
        environment: "${{ parameters.environment }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  name: LookupSubscription
                  displayName: "Lookup Existing Subscription"
                  inputs:
                    azureSubscription: "$(azureServiceConnection)"
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      bash $(scriptsPath)/lookup-subscription.sh \
                        "${{ parameters.workloadAlias }}" \
                        "${{ parameters.environment }}" \
                        "${{ parameters.locationCode }}" \
                        "${{ parameters.instanceNumber }}"

                - task: AzureCLI@2
                  displayName: "Deploy Subscription Vending"
                  inputs:
                    azureSubscription: "$(azureServiceConnection)"
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      # Construct billing scope from variable group values
                      BILLING_SCOPE=""
                      if [ -n "$(billingAccountId)" ]; then
                        if [ -n "$(invoiceSectionId)" ] && [ -n "$(billingProfileId)" ]; then
                          # MCA billing scope format (requires billing profile)
                          BILLING_SCOPE="/providers/Microsoft.Billing/billingAccounts/$(billingAccountId)/billingProfiles/$(billingProfileId)/invoiceSections/$(invoiceSectionId)"
                        elif [ -n "$(enrollmentAccountId)" ]; then
                          # EA billing scope format
                          BILLING_SCOPE="/providers/Microsoft.Billing/billingAccounts/$(billingAccountId)/enrollmentAccounts/$(enrollmentAccountId)"
                        fi
                      fi

                      # Get existing subscription ID from lookup step (may be empty)
                      EXISTING_SUB_ID="$(LookupSubscription.EXISTING_SUBSCRIPTION_ID)"

                      # Deployment name for tracking
                      DEPLOYMENT_NAME="sub-vending-$(Build.BuildNumber)"

                      echo "Starting subscription vending deployment: ${DEPLOYMENT_NAME}"
                      echo "Note: Subscription creation is asynchronous and may take 30-90 minutes to complete."

                      # Start deployment with --no-wait to avoid blocking on subscription provisioning
                      az deployment tenant create \
                        --name "${DEPLOYMENT_NAME}" \
                        --location "$(deploymentLocation)" \
                        --template-file "$(templateFile)" \
                        --parameters "$(parametersFile)" \
                        --parameters projectName="${{ parameters.projectName }}" \
                        --parameters managementGroupId="${{ parameters.managementGroupId }}" \
                        --parameters billingScope="$BILLING_SCOPE" \
                        --parameters workload="${{ parameters.workload }}" \
                        --parameters workloadAlias="${{ parameters.workloadAlias }}" \
                        --parameters environment="${{ parameters.environment }}" \
                        --parameters locationCode="${{ parameters.locationCode }}" \
                        --parameters instanceNumber="${{ parameters.instanceNumber }}" \
                        --parameters owner="${{ parameters.owner }}" \
                        --parameters managedBy="${{ parameters.managedBy }}" \
                        --parameters existingSubscriptionId="$EXISTING_SUB_ID" \
                        --no-wait

                      if [ $? -ne 0 ]; then
                        echo "##[error]Failed to start deployment"
                        exit 1
                      fi

                      echo "✓ Deployment started successfully. Polling for completion..."

                      # Poll deployment status until it completes or times out
                      # Subscription provisioning can take 30-90 minutes
                      MAX_WAIT_SECONDS=5400  # 90 minutes
                      POLL_INTERVAL=60       # Check every 60 seconds
                      ELAPSED=0
                      LAST_STATUS=""

                      while [ $ELAPSED -lt $MAX_WAIT_SECONDS ]; do
                        # Get current deployment status
                        STATUS=$(az deployment tenant show \
                          --name "${DEPLOYMENT_NAME}" \
                          --query "properties.provisioningState" \
                          --output tsv 2>/dev/null || echo "Unknown")

                        # Only log when status changes to reduce noise
                        if [ "$STATUS" != "$LAST_STATUS" ]; then
                          echo "Deployment status: ${STATUS} (elapsed: ${ELAPSED}s / ${MAX_WAIT_SECONDS}s)"
                          LAST_STATUS="$STATUS"
                        fi

                        # Check if deployment completed
                        if [ "$STATUS" == "Succeeded" ]; then
                          echo "##[section]✓ Deployment completed successfully!"
                          
                          # Get deployment outputs for logging
                          OUTPUTS=$(az deployment tenant show \
                            --name "${DEPLOYMENT_NAME}" \
                            --query "properties.outputs" \
                            --output json 2>/dev/null || echo "{}")
                          
                          if [ "$OUTPUTS" != "{}" ] && [ -n "$OUTPUTS" ]; then
                            echo "Deployment outputs:"
                            echo "$OUTPUTS" | jq '.' 2>/dev/null || echo "$OUTPUTS"
                          fi
                          
                          exit 0
                        elif [ "$STATUS" == "Failed" ]; then
                          echo "##[error]Deployment failed!"
                          
                          # Get error details
                          ERROR=$(az deployment tenant show \
                            --name "${DEPLOYMENT_NAME}" \
                            --query "properties.error" \
                            --output json 2>/dev/null || echo "{}")
                          
                          if [ "$ERROR" != "{}" ] && [ -n "$ERROR" ]; then
                            echo "Error details:"
                            echo "$ERROR" | jq '.' 2>/dev/null || echo "$ERROR"
                          fi
                          
                          exit 1
                        elif [ "$STATUS" == "Canceled" ]; then
                          echo "##[error]Deployment was canceled"
                          exit 1
                        fi

                        # Wait before next poll
                        sleep $POLL_INTERVAL
                        ELAPSED=$((ELAPSED + POLL_INTERVAL))
                      done

                      # Timeout reached
                      echo "##[error]Deployment did not complete within ${MAX_WAIT_SECONDS} seconds (90 minutes)"
                      echo "Current status: ${STATUS}"
                      echo "The deployment may still be in progress. Check Azure Portal for current status."
                      echo "Deployment name: ${DEPLOYMENT_NAME}"
                      exit 1
