# Azure Pipeline to deploy Subscription Vending
# This pipeline deploys the sub-vending Bicep template at the management group scope
# This pipeline is reusable and can be triggered with parameters
#
# =============================================================================
# RBAC REQUIREMENTS
# =============================================================================
# The service principal used by the Azure service connection requires:
#
#   1. Owner - At Tenant Root MG for subscription creation and MG assignment
#   2. Billing Permissions - Invoice Section Contributor (MCA) or
#                            Enrollment Account Administrator (EA)
#
# Azure RBAC assignment:
#
#   SP_OBJECT_ID="<service-principal-object-id>"
#   TENANT_ROOT_MG=$(az account management-group list \
#     --query "[?displayName=='Tenant Root Group'].name" -o tsv)
#
#   az role assignment create --assignee "$SP_OBJECT_ID" \
#     --role "Owner" \
#     --scope "/providers/Microsoft.Management/managementGroups/$TENANT_ROOT_MG"
#
# Billing permissions must be assigned via Azure Portal:
#   1. Go to Cost Management + Billing
#   2. Navigate to your billing account/invoice section
#   3. Add the SP as Invoice Section Contributor (MCA) or
#      Enrollment Account Administrator (EA)
#
# See docs/RBAC-Requirements.md for full documentation.
# =============================================================================

trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: common-variables
  - name: bicepPath
    value: "code/bicep/sub-vending"
  - name: templateFile
    value: "$(bicepPath)/sub-vending.bicep"
  - name: parametersFile
    value: "$(bicepPath)/sub-vending.bicepparam"

parameters:
  - name: subscriptionDisplayName
    displayName: "Subscription Display Name"
    type: string
    default: ""
  - name: workloadAlias
    displayName: "Workload Alias"
    type: string
    default: ""
  - name: environment
    displayName: "Environment"
    type: string
    default: ""
    values:
      - nonprod
      - dev
      - test
      - uat
      - staging
      - prod
      - live
  - name: locationCode
    displayName: "Location Code (e.g., cac for canada central)"
    type: string
    default: "cac"
  - name: instanceNumber
    displayName: "Instance Number (e.g., 001 for the first instance)"
    type: string
    default: ""
  - name: managementGroupId
    displayName: "Management Group ID"
    type: string
    default: ""
    values:
      - $(azureTenantId)
      - "mg-platform"
      - "mg-landing-zone"
      - "mg-sandbox"
      - "mg-decommissioned"
      - "mg-management"
      - "mg-connectivity"
      - "mg-corp-prod"
      - "mg-corp-non-prod"
      - "mg-online-prod"
      - "mg-online-non-prod"
  - name: workload
    displayName: "Workload Type"
    type: string
    default: "Production"
    values:
      - Production
      - DevTest
  - name: managedBy
    displayName: "Managed By"
    type: string
    default: "$(managedBy)"
  - name: owner
    displayName: "Owner"
    type: string
    default: "$(defaultOwner)"
  - name: deploymentStage
    displayName: "Pipeline Stage to Run"
    type: string
    default: "WhatIf"
    values:
      - Validation
      - WhatIf
      - Deploy

stages:
  - stage: Validate
    displayName: "Validate Bicep Template"
    # Runs for: Validation, WhatIf, Deploy (all options)
    jobs:
      - job: ValidateBicep
        displayName: "Validate Bicep"
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "Validate Subscription Vending Deployment"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                # Construct billing scope from variable group values
                BILLING_SCOPE=""
                if [ -n "$(billingAccountId)" ]; then
                  if [ -n "$(invoiceSectionId)" ]; then
                    # MCA billing scope format
                    BILLING_SCOPE="/providers/Microsoft.Billing/billingAccounts/$(billingAccountId)/invoiceSections/$(invoiceSectionId)"
                  elif [ -n "$(enrollmentAccountId)" ]; then
                    # EA billing scope format
                    BILLING_SCOPE="/providers/Microsoft.Billing/billingAccounts/$(billingAccountId)/enrollmentAccounts/$(enrollmentAccountId)"
                  fi
                fi

                PARAMS=""
                if [ -n "${{ parameters.subscriptionDisplayName }}" ]; then
                  PARAMS="$PARAMS --parameters subscriptionDisplayName='${{ parameters.subscriptionDisplayName }}'"
                fi
                if [ -n "${{ parameters.managementGroupId }}" ]; then
                  PARAMS="$PARAMS --parameters managementGroupId='${{ parameters.managementGroupId }}'"
                fi
                if [ -n "$BILLING_SCOPE" ]; then
                  PARAMS="$PARAMS --parameters billingScope='$BILLING_SCOPE'"
                fi
                if [ -n "${{ parameters.workload }}" ]; then
                  PARAMS="$PARAMS --parameters workload='${{ parameters.workload }}'"
                fi
                if [ -n "${{ parameters.workloadAlias }}" ]; then
                  PARAMS="$PARAMS --parameters workloadAlias='${{ parameters.workloadAlias }}'"
                fi
                if [ -n "${{ parameters.environment }}" ]; then
                  PARAMS="$PARAMS --parameters environment='${{ parameters.environment }}'"
                fi
                if [ -n "${{ parameters.locationCode }}" ]; then
                  PARAMS="$PARAMS --parameters locationCode='${{ parameters.locationCode }}'"
                fi
                if [ -n "${{ parameters.instanceNumber }}" ]; then
                  PARAMS="$PARAMS --parameters instanceNumber='${{ parameters.instanceNumber }}'"
                fi
                if [ -n "${{ parameters.owner }}" ]; then
                  PARAMS="$PARAMS --parameters owner='${{ parameters.owner }}'"
                fi
                if [ -n "${{ parameters.managedBy }}" ]; then
                  PARAMS="$PARAMS --parameters managedBy='${{ parameters.managedBy }}'"
                fi

                az deployment mg validate \
                  --management-group-id $(azureTenantId) \
                  --location $(deploymentLocation) \
                  --template-file $(templateFile) \
                  --parameters $(parametersFile) \
                  $PARAMS

  - stage: WhatIf
    displayName: "What-If Analysis"
    dependsOn:
      - Validate
    # Runs for: WhatIf, Deploy
    condition: |
      and(
        eq(dependencies.Validate.result, 'Succeeded'),
        in('${{ parameters.deploymentStage }}', 'WhatIf', 'Deploy')
      )
    jobs:
      - job: WhatIfAnalysis
        displayName: "What-If"
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "What-If Subscription Vending Deployment"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                # Construct billing scope from variable group values
                BILLING_SCOPE=""
                if [ -n "$(billingAccountId)" ]; then
                  if [ -n "$(invoiceSectionId)" ]; then
                    # MCA billing scope format
                    BILLING_SCOPE="/providers/Microsoft.Billing/billingAccounts/$(billingAccountId)/invoiceSections/$(invoiceSectionId)"
                  elif [ -n "$(enrollmentAccountId)" ]; then
                    # EA billing scope format
                    BILLING_SCOPE="/providers/Microsoft.Billing/billingAccounts/$(billingAccountId)/enrollmentAccounts/$(enrollmentAccountId)"
                  fi
                fi

                PARAMS=""
                if [ -n "${{ parameters.subscriptionDisplayName }}" ]; then
                  PARAMS="$PARAMS --parameters subscriptionDisplayName='${{ parameters.subscriptionDisplayName }}'"
                fi
                if [ -n "${{ parameters.workloadAlias }}" ]; then
                  PARAMS="$PARAMS --parameters workloadAlias='${{ parameters.workloadAlias }}'"
                fi
                if [ -n "${{ parameters.environment }}" ]; then
                  PARAMS="$PARAMS --parameters environment='${{ parameters.environment }}'"
                fi
                if [ -n "${{ parameters.locationCode }}" ]; then
                  PARAMS="$PARAMS --parameters locationCode='${{ parameters.locationCode }}'"
                fi
                if [ -n "${{ parameters.instanceNumber }}" ]; then
                  PARAMS="$PARAMS --parameters instanceNumber='${{ parameters.instanceNumber }}'"
                fi
                if [ -n "${{ parameters.managementGroupId }}" ]; then
                  PARAMS="$PARAMS --parameters managementGroupId='${{ parameters.managementGroupId }}'"
                fi
                if [ -n "$BILLING_SCOPE" ]; then
                  PARAMS="$PARAMS --parameters billingScope='$BILLING_SCOPE'"
                fi
                if [ -n "${{ parameters.workload }}" ]; then
                  PARAMS="$PARAMS --parameters workload='${{ parameters.workload }}'"
                fi
                if [ -n "${{ parameters.owner }}" ]; then
                  PARAMS="$PARAMS --parameters owner='${{ parameters.owner }}'"
                fi
                if [ -n "${{ parameters.managedBy }}" ]; then
                  PARAMS="$PARAMS --parameters managedBy='${{ parameters.managedBy }}'"
                fi

                az deployment mg what-if \
                  --management-group-id $(azureTenantId) \
                  --location $(deploymentLocation) \
                  --template-file $(templateFile) \
                  --parameters $(parametersFile) \
                  $PARAMS

  - stage: Deploy
    displayName: "Deploy Subscription Vending"
    dependsOn:
      - Validate
      - WhatIf
    # Runs for: Deploy only
    condition: |
      and(
        eq(dependencies.Validate.result, 'Succeeded'),
        in(dependencies.WhatIf.result, 'Succeeded', 'Skipped'),
        eq('${{ parameters.deploymentStage }}', 'Deploy')
      )
    jobs:
      - deployment: DeploySubscriptionVending
        displayName: "Deploy Subscription Vending"
        environment: "subscription-vending"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: "Deploy Subscription Vending"
                  inputs:
                    azureSubscription: "$(azureServiceConnection)"
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      # Construct billing scope from variable group values
                      BILLING_SCOPE=""
                      if [ -n "$(billingAccountId)" ]; then
                        if [ -n "$(invoiceSectionId)" ]; then
                          # MCA billing scope format
                          BILLING_SCOPE="/providers/Microsoft.Billing/billingAccounts/$(billingAccountId)/invoiceSections/$(invoiceSectionId)"
                        elif [ -n "$(enrollmentAccountId)" ]; then
                          # EA billing scope format
                          BILLING_SCOPE="/providers/Microsoft.Billing/billingAccounts/$(billingAccountId)/enrollmentAccounts/$(enrollmentAccountId)"
                        fi
                      fi

                      PARAMS=""
                      if [ -n "${{ parameters.subscriptionDisplayName }}" ]; then
                        PARAMS="$PARAMS --parameters subscriptionDisplayName='${{ parameters.subscriptionDisplayName }}'"
                      fi
                      if [ -n "${{ parameters.workloadAlias }}" ]; then
                        PARAMS="$PARAMS --parameters workloadAlias='${{ parameters.workloadAlias }}'"
                      fi
                      if [ -n "${{ parameters.environment }}" ]; then
                        PARAMS="$PARAMS --parameters environment='${{ parameters.environment }}'"
                      fi
                      if [ -n "${{ parameters.locationCode }}" ]; then
                        PARAMS="$PARAMS --parameters locationCode='${{ parameters.locationCode }}'"
                      fi
                      if [ -n "${{ parameters.instanceNumber }}" ]; then
                        PARAMS="$PARAMS --parameters instanceNumber='${{ parameters.instanceNumber }}'"
                      fi
                      if [ -n "${{ parameters.managementGroupId }}" ]; then
                        PARAMS="$PARAMS --parameters managementGroupId='${{ parameters.managementGroupId }}'"
                      fi
                      if [ -n "$BILLING_SCOPE" ]; then
                        PARAMS="$PARAMS --parameters billingScope='$BILLING_SCOPE'"
                      fi
                      if [ -n "${{ parameters.workload }}" ]; then
                        PARAMS="$PARAMS --parameters workload='${{ parameters.workload }}'"
                      fi
                      if [ -n "${{ parameters.owner }}" ]; then
                        PARAMS="$PARAMS --parameters owner='${{ parameters.owner }}'"
                      fi
                      if [ -n "${{ parameters.managedBy }}" ]; then
                        PARAMS="$PARAMS --parameters managedBy='${{ parameters.managedBy }}'"
                      fi

                      az deployment mg create \
                        --name 'sub-vending-$(Build.BuildNumber)' \
                        --management-group-id $(azureTenantId) \
                        --location $(deploymentLocation) \
                        --template-file $(templateFile) \
                        --parameters $(parametersFile) \
                        $PARAMS
